# Everything needed for package installation, regardless of the host
---
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"
- name: Update Homebrew cache
  homebrew: update_homebrew=yes 
  when: ansible_os_family == "Darwin"
