- name: Ensure apache and modules are at the latest version
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
  - apache2
  - libapache2-mod-wsgi
  when: ansible_os_family == "Debian"

- name: Enable Apache SSL module
  command: a2enmod ssl

- name: Enable Apache WSGI module
  command: a2enmod wsgi

- name: Copy tailored Apache VHost config file
  template: src=apache2_config.j2 dest=/etc/apache2/sites-available/{{ servername }}.conf

- name: Copy tailored wsgi.py file
  template: src=wsgi.py.j2 dest={{ www_base_dir }}/FuzzEd/wsgi.py

- name: Set link to Apache VHost config file
  file: src=/etc/apache2/sites-available/{{ servername }}.conf dest=/etc/apache2/sites-enabled/{{ servername }}.conf state=link force=yes

- name: Create directory for SSL certs
  file: path=/etc/apache2/ssl state=directory

- name: Generate SSL cert, if not existent
  command: openssl req -new -nodes -x509 -subj "/CN={{ servername }}" -days 3650 -keyout "{{ ssl_key }}" -out "{{ ssl_cert }}" -extensions v3_ca 
  args: 
    creates: "{{ ssl_cert }}" 

- name: Ensure that Apache config is correct
  command: apache2ctl configtest
  become: yes

- name: Ensure Apache is restarted
  service: name=apache2 state=restarted
  become: yes
