---
- name: Perform database backup
  command: pg_dump -c -f /tmp/{{ db_name }}_backup.sql {{ db_name }}
  sudo: yes
  sudo_user: postgres

#- name: Download FuzzEd release to server
#  get_url: url=https://github.com/troeger/fuzzed/releases/download/{{release_version}}/FuzzEd-{{release_version}}.tar.gz dest={{ install_base_dir }} 

- name: Upload FuzzEd release to server
  copy: src=../dist/FuzzEd-{{release_version}}.tar.gz dest={{ install_base_dir }}/

- name: Create target directory for unarchiving
  file: path={{ install_base_dir }}/{{ release_version }}/ state=directory

- name: Unarchive release package on server
  unarchive: copy=no src={{ install_base_dir }}/FuzzEd-{{release_version}}.tar.gz dest={{ install_base_dir }}/{{ release_version }}

- name: Adjusting links for pointing to download package
  file: src={{ install_base_dir }}/{{ release_version }} dest={{ www_base_dir }} state=link force=yes

# This separate step avoids an issue were the first migration fails with an "auth_user" issue
- name: Perform database migration
  django_manage: command="migrate auth"
                 app_path={{ www_base_dir }}
                 virtualenv={{ virtualenvpath }}

- name: Perform database migration
  django_manage: command=migrate
                 app_path={{ www_base_dir }}
                 virtualenv={{ virtualenvpath }}

- name: Ensure apache and modules are at the latest version
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
  - apache2
  - libapache2-mod-wsgi
  when: ansible_os_family == "Debian"

- name: How can we reach that thing ?
  debug: msg="Using {{ servername }} as address for web presence"

