filter:
    paths:
        - 'FuzzEd/*'
        - 'executor/*'
    excluded_paths:
        - '*/migrations/*'
        - '*/static/*'
        - '*/fixtures/*'
        - 'FuzzEd/tests/js-tests/*'
checks:
    python:
        code_rating: true
        duplicate_code: true
