filter:
    paths:
        - 'front/FuzzEd/*'
    excluded_paths:
        - '*/migrations/*'
        - '*/static/*'
        - '*/fixtures/*'
        - '*/js-tests/*'
checks:
    python:
        code_rating: true
        duplicate_code: true
