version: '3'

services:
  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: ore
      POSTGRES_USER: ore
      POSTGRES_DB: ore
    volumes:
      - postgres-volume:/var/lib/postgresql/data  
  front:
    image: troeger/ore_front
    environment:
      DJANGO_CONFIGURATION: Dev
      # FUZZED_SECRET_KEY: "{{ ansible_product_uuid }}"
      # FUZZED_NAME: "{{ db_name }}"
      # FUZZED_USER: "{{ db_user }}"
      # FUZZED_PASSWORD:   "{{ db_pw }}"
      # FUZZED_HOST: "{{ db_host }}"
      # FUZZED_PORT: "{{ db_port }}"
      # FUZZED_SERVER: "{{ servername }}"
      # FUZZED_SERVER_URL: "https://{{ servername }}"
      # FUZZED_SERVER_EMAIL: XXX
      # FUZZED_ADMIN_EMAIL: XXX
      # FUZZED_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY    : "XXX"
      # FUZZED_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET : "XXX"
      # FUZZED_SOCIAL_AUTH_TWITTER_KEY          : "XXX"
      # FUZZED_SOCIAL_AUTH_TWITTER_SECRET       : "XXX"
      # FUZZED_SOCIAL_AUTH_LIVE_CLIENT_ID       : "XXX"
      # FUZZED_SOCIAL_AUTH_LIVE_CLIENT_SECRET   : "XXX"
      # FUZZED_SOCIAL_AUTH_YAHOO_OAUTH2_KEY     : "XXX"
      # FUZZED_SOCIAL_AUTH_YAHOO_OAUTH2_SECRET  : "XXX"
      # FUZZED_SOCIAL_AUTH_GITHUB_KEY           : "XXX"
      # FUZZED_SOCIAL_AUTH_GITHUB_SECRET        : "XXX"
    build: 
      context: ./front/
    tty: true
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - data-volume:/data
  back:
    image: troeger/ore_back
    build: 
      context: ./back/
    tty: true
    depends_on:
      - front

volumes:
  data-volume:
  postgres-volume:
