version: '3'

services:
  db:
    image: postgres:9
    container_name: ore-db
    environment:
      POSTGRES_PASSWORD: ore
      POSTGRES_USER: ore
      POSTGRES_DB: ore
    volumes:
      - postgres-volume:/var/lib/postgresql/data  
  front:
    image: troeger/ore-front
    container_name: ore-front
    build: 
      context: .
      dockerfile: ./frontend/docker/Dockerfile
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./frontend:/ore-front
      - ./backends:/ore-back
  back:
    image: troeger/ore-back
    container_name: ore-back
    build: 
      context: .
      dockerfile: ./backends/Dockerfile
    tty: true

volumes:
  data-volume:
  postgres-volume:
