---
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"
- name: Ensure PIP is installed
  apt: pkg=python-pip state=latest
  when: ansible_os_family == "Debian"

# Put this into the dev folder
- name: Ensure Fabric is installed
  pip: name=fabric state=latest
