---
- name: Perform database backup  
  command: pg_dump -c -f /tmp/dbackup.sql fuzzed
  sudo: yes
  sudo_user: postgres
- name: Ensure latest FuzzEd version is installed
  get_url: url=http://github.com/XXX dest=/tmp mode=0440
- name: Unarchive FuzzEd download package
  unarchive: src=/tmp/XXX dest=/var/www/fuzzed/XXX
- name: Adjusting links for pointing to download package 
  file: dest=/var/www/fuzzed/XXX src=/var/www/fuzzed/current owner=www-data group=www-data state=link
- name: Perform database migration  
  command: cd /var/www/fuzzed.org/www/; ./manage.py syncdb --migrate
  sudo: yes
- name: Ensure that Apache config is correct  
  command: apache2ctl configtest
  sudo: yes
- name: Ensure Apache is restarted
  service: name=fuzzed-backend state=restarted
