---
- name: Ensure CMake is installed (Debian)
  apt: name=cmake state=present
  become: yes
  when: ansible_os_family == "Debian"
- name: Ensure CMake is installed (Darwin)
  homebrew: name=cmake state=present
  when: ansible_os_family == "Darwin"
