---
- name: Ensure .less file compiler is installed (Debian)
  npm:  name=less global=yes
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Ensure .less file compiler is installed (Darwin)
  npm:  name=less global=yes
  when: ansible_os_family == "Darwin"

