---
- name: Ensure Django is installed
  pip: name=django version=1.8.18

- name: Ensure Django Social Auth is installed
  pip: name=python-social-auth version=0.2.21

- name: Ensure Django SocialAuth dependencies are installed
  pip: name={{item}} 
  with_items:
  - python-openid
  - python-oauth2

- name: Ensure Django Require is installed
  pip: name=django-require

- name: Ensure Django Robots is installed
  pip: name=django-robots

- name: Ensure Django Tastypie is installed
  pip: name=django-tastypie

- name: Ensure Django configurations is installed
  pip: name=django-configurations

