---
- name: Ensure LaTex is installed (Debian)
  apt: pkg=texlive state=latest
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Check if LaTex was manually installed
  stat: path=/usr/texbin/dvips
  register: tex

- name: Check for DVIPS
  fail: msg="DVIPS is not available. Please install a Tex distribution."
  when: tex.stat.isfile is defined and tex.stat.isfile == true
