---
- include: apache2.yml
- include: db.yml

- name: Perform database backup
  command: pg_dump -c -f /tmp/{{ db_name }}_backup.sql {{ db_name }}
  sudo: yes
  sudo_user: postgres

#- name: Download FuzzEd release to server
#  get_url: url=https://github.com/troeger/fuzzed/releases/download/{{release_version}}/FuzzEd-{{release_version}}.tar.gz dest={{ install_base_dir }} 

- name: Upload FuzzEd release to server
  copy: src=../dist/FuzzEd-{{release_version}}.tar.gz dest={{ install_base_dir }}

- name: Create target directory for unarchiving
  file: path={{ install_base_dir }}/{{ release_version }} state=directory

- name: Unarchive release package on server
  unarchive: copy=no src={{ install_base_dir }}/FuzzEd-{{release_version}}.tar.gz dest={{ install_base_dir }}/{{ release_version }}

- name: Adjusting links for pointing to download package
  file: src={{ install_base_dir }}/{{ release_version }} dest={{ www_base_dir }} state=link force=yes

- name: Perform database migration
  django_manage: command=migrate
                 app_path={{ www_base_dir }}
                 virtualenv={{ virtualenvpath }}

- name: Copy Apache VHost config file
  template: src=/install_frontend/tasks/apache2_config.j2 dest=/etc/apache2/sites-available/{{ servername }}

- name: Set link to Apache VHost config file
  file: src=/etc/apache2/sites-available/{{ servername }} dest=/etc/apache2/sites-enabled/{{ servername }} state=link force=yes

- name: Ensure that Apache config is correct
  command: apache2ctl configtest
  sudo: yes

- name: Ensure Apache is restarted
  service: name=apache2 state=restarted
  sudo: yes
