---
- name: Install PostgreSQL 
  apt: pkg=postgresql state=latest
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL native client 
  apt: name={{ item }} state=latest
  with_items:
  - postgresql-client
  - libpq-dev
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL Python client 
  pip: name=psycopg2 virtualenv={{ virtualenvpath }}

# Commented out, due to missing VirtualEnv support:
# http://stackoverflow.com/questions/29728530/using-ansible-postgresql-user-with-psycopg2-from-virtualenv
#
# For the moment, you need to do that manually

#- name: Install PostgreSQL user
#  sudo: yes
#  sudo_user: postgres
#  postgresql_user: name=fuzzed password=fuzzed role_attr_flags=NOSUPERUSER
#  when: ansible_os_family == "Debian"

#- name: Install PostgreSQL database
#  sudo: yes
#  sudo_user: postgres
#  postgresql_db: name=fuzzed owner=fuzzed
#  when: ansible_os_family == "Debian"



