---
- name: Ensure Django is installed
  sudo: yes
  easy_install: name=django
- name: Ensure Django SocialAuth and dependencies are installed
  sudo: yes
  easy_install: name={{item}}
  with_items:
  - python-social-auth
  - python-openid
  - python-oauth2
- name: Ensure Django Require is installed
  sudo: yes
  easy_install: name=django-require 
- name: Ensure Django Tastypie is installed
  sudo: yes
  pip: name=git+https://github.com/django-tastypie/django-tastypie.git 
- name: Ensure Django Wiki and dependencies are installed
  sudo: yes
  easy_install: name={{item}}
  with_items:
  - djiki
  - py-wikimarkup
  - defusedxml
- name: Ensure Django configurations is installed
  sudo: yes
  pip: name=git+https://github.com/jezdez/django-configurations.git
- name: Ensure OAuth client libary is installed for testing purposes
  sudo: yes
  easy_install: name=requests_oauthlib 
