---
- name: Configure developer machine
  hosts: localhost
  user: root

  roles:
    - all
    - build_fuzzed
    - build_less_code
    - build_xsd_code
    - build_cpp_code
    - run_fuzzed_be
    - run_fuzzed_fe
    - test_fuzzed
