---
- name: Configure minimal local Web developer machine
  hosts: localdev
  user: root

  roles:
    - all
    - build_fuzzed
    - build_less_code
    - build_xsd_code
    - run_fuzzed_fe

- name: Configure Vagrant developer machine
  hosts: vagrantdev
  user: root

  roles:
    - all
    - build_fuzzed
    - build_less_code
    - build_xsd_code
    - build_cpp_code
    - run_fuzzed_be
    - run_fuzzed_fe
    - test_fuzzed
