---
- name: Configure local Web developer machine
  hosts: localdev
  user: root

  roles:
    - all
    - build_fuzzed
    - build_less_code
    - build_xsd_code
    - run_fuzzed_fe
    - test_fuzzed

  vars_prompt:
    - name: "virtualenvpath"
      prompt: "Path for VirtualEnv environment"
      private: no
      default: "~/fuzzed_venv/"


- name: Configure Vagrant developer machine
  hosts: vagrantdev
  user: root

  roles:
    - all
    - build_fuzzed
    - build_less_code
    - build_xsd_code
    - build_cpp_code
    - run_fuzzed_be
    - run_fuzzed_fe
    - test_fuzzed
