---
- hosts: webservers
  remote_user: root
  tasks:
  - name: Update APT cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Ensure apache is at the latest version
    apt: pkg=apache2 state=latest
  - name: Ensure apache is running
    service: name=apache2 state=started
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted