---
- name: Configure production web servers
  hosts: webservers
  user: root
  environment: env_vars # needed for making ./manage.py workable, comes from host config
  vars_prompt:
    - name: "release_version"
      prompt: "FuzzEd Github release version"
      private: no
  roles:
    - common
    - web
    - install_frontend

- name: Configure production backend servers
  hosts: backendservers
  user: root

  roles:
    - common
    - backend
    - install_backend
