---
- name: Configure production web servers
  hosts: webservers
  user: root

  roles:
    - oauth

- name: Configure production backend servers
  hosts: backendservers
  user: root

  roles:
    - oauth

- name: Configure developer machine
  hosts: devmachine
  user: root

  roles:
    - oauth
