# Everything needed for package installation, regardless of the host
---
- name: Update APT cache (Debian)
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Update Homebrew cache (Darwin)
  homebrew: update_homebrew=yes
  when: ansible_os_family == "Darwin"

- name: Ensure GIT is installed (Debian)
  apt: pkg=git state=latest
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Ensure GIT is installed (Darwin)
  homebrew: name=git state=present
  when: ansible_os_family == "Darwin"

- include: python.yml