# FE and BE both have their Python parts, so we make it mandatory everywhere
---
- name: Ensure Python Dev is installed (Debian)
  apt: pkg=python-dev state=latest
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Ensure Python PIP is installed (Debian)
  apt: pkg=python-pip state=latest
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Ensure VirtualEnv is installed
  pip: name=virtualenv state=present
