apiVersion: apps/v1
kind: Deployment
metadata:
  name: ore-front
  labels:
    app.kubernetes.io/name: ore
    app.kubernetes.io/component: front
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ore
      app.kubernetes.io/component: front
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ore
        app.kubernetes.io/component: front
    spec:
      containers:
      - name: ore-front
        image: troeger/ore-front:0.8.3
        ports:
        - containerPort: 80
        env:
        - name:  ORE_BACKEND_DAEMON
          value: http://ore-back:8000
        - name:  ORE_SERVER_URL
          value: https://live.ore-project.org
        - name:  ORE_SERVER
          value: live.ore-project.org
        - name:  ORE_DB_NAME
          value: ore 
        - name:  ORE_DB_USER
          value: ore 
        - name:  ORE_DB_PASSWORD
          value: ore 
        - name:  ORE_DB_HOST
          value: ore-db
        - name:  ORE_DB_PORT   # need to set that, otherwise overwritten by older K8S (see #60999)
          value: "5432"
        - name: ORE_SECRET_KEY
          value: 28ehfwoifqh!##asdasu
        - name: ORE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
          value: 907559039211-4qan8v4o12vh9r6ifb4295efmu4ll9fh.apps.googleusercontent.com
        - name: ORE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
          value: nvP3Lf0k0JyZZPruG0hex9fh
        - name: ORE_SOCIAL_AUTH_TWITTER_KEY
          value: E0TOSwoGhncQtm0cP19pFbHfb
        - name: ORE_SOCIAL_AUTH_TWITTER_SECRET
          value: c7Ko25wkhrUMd2TeYpHR5YTQzzHw1l0vaVer5XVD2zuVdS17ta
        - name: ORE_SOCIAL_AUTH_GITHUB_KEY
          value: a5a3dff5f02053503068
        - name: ORE_SOCIAL_AUTH_GITHUB_SECRET
          value: 822b855cc315229a5d488def5afdb4ce21b77820
---
apiVersion: v1
kind: Service
metadata:
  name: ore-front
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: ore
    app.kubernetes.io/component: front
