apiVersion: apps/v1
kind: Deployment
metadata:
  name: ore-front
  labels:
    app.kubernetes.io/name: ore
    app.kubernetes.io/component: front
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ore
      app.kubernetes.io/component: front
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ore
        app.kubernetes.io/component: front
    spec:
      containers:
      - name: ore-front
        image: troeger/ore-front:0.8.4
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: ore-config
        env:
        - name:  ORE_DB_NAME
          value: ore 
        - name:  ORE_DB_USER
          value: ore 
        - name:  ORE_DB_PASSWORD
          value: ore 
        - name:  ORE_DB_HOST
          value: ore-db
        - name:  ORE_DB_PORT   # need to set that, otherwise overwritten by older K8S (see #60999)
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: ore-front
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: ore
    app.kubernetes.io/component: front
