---
# Installing less via npm: no brew on Darwin, too old in Linux apt
- name: Ensure NPM is installed (Debian)
  sudo: yes
  apt: pkg=npm state=present
  when: ansible_os_family == "Debian"

- name: Ensure NPM is installed (Darwin)
  homebrew: pkg=npm state=present
  when: ansible_os_family == "Darwin"

